name: Publish casks on schedule

on:
  workflow_dispatch:
  schedule:
    # Once every hour
    - cron: "*/60 * * * *"

concurrency:
  group: autopublish
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autopublish:
    if: github.repository == 'kiblik/homebrew-eid-sk'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run automerge
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          brew pr-automerge --verbose \
                            --publish \
                            --tap kiblik/eid-sk \
                            --workflow=publish-commit-casks.yml \
                            --without-labels="do not merge,new cask,automerge-skip"
