name: Bump formulae

on:
  push:
    paths:
      - .github/workflows/bump-formulae.yml
  schedule:
    - cron: "*/30 * * * *"

concurrency:
  group: bump-formulae
  cancel-in-progress: true

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

permissions:
  contents: read

jobs:
  bump-formulae:
    if: startsWith(github.repository, 'kiblik/homebrew-')
    runs-on: macos-11.0
    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        with:
          # Custom GitHub access token with only the 'public_repo' scope enabled
          token: ${{secrets.TOKEN}}
          # Bump only these formulae if outdated
          formulae: |
            eid-sk
#            eid-sk-d-launcher1
#            eid-sk-disig-web-signer